[build-system]
requires = ["poetry-core>=2.3.2"]
build-backend = "poetry.core.masonry.api"

[project]
name = "stethoscope"
version = "0.0.0"
readme = "README.md"
description = "A lightweight application licensing server."
authors = [{ name = "Better HPC LLC" }]
keywords = ["Better", "HPC", "stethoscope"]
requires-python = ">=3.14,<4"
dependencies = [
    "django==6.0.4",
    "django-environ==0.13.0",
    "django-jazzmin==3.0.4",
    "django-unfold==0.90.0",
    "djangorestframework==3.17.1",
    "psycopg2-binary==2.9.11",
    "servestatic==4.3.0",
    "uvicorn==0.45.0",
]

[project.scripts]
stethoscope = "stethoscope.manage:main"
