# Generated by Django 6.0.4 on 2026-04-26 16:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='licensing_a_name_04cea2_idx'), models.Index(fields=['version'], name='licensing_a_version_37092b_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='unique_application_name_version')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('billing_address_line_1', models.CharField(blank=True, max_length=255)),
                ('billing_address_line_2', models.CharField(blank=True, max_length=255)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_state', models.CharField(blank=True, max_length=100)),
                ('billing_postal_code', models.CharField(blank=True, max_length=20)),
                ('billing_country', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='licensing_c_name_eaa729_idx'), models.Index(fields=['email'], name='licensing_c_email_369baf_idx')],
            },
        ),
        migrations.CreateModel(
            name='LicenseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64)),
                ('token_plain', models.CharField(editable=False, max_length=64, null=True)),
                ('retrieve_id', models.CharField(max_length=64, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retrieved_at', models.DateTimeField(null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_tokens', to='licensing.application')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_tokens', to='licensing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='licensing.licensetoken')),
            ],
        ),
        migrations.AddIndex(
            model_name='licensetoken',
            index=models.Index(fields=['token'], name='licensing_l_token_9b8c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='licensetoken',
            index=models.Index(fields=['customer'], name='licensing_l_custome_43fa29_idx'),
        ),
        migrations.AddIndex(
            model_name='licensetoken',
            index=models.Index(fields=['application'], name='licensing_l_applica_14908c_idx'),
        ),
        migrations.AddIndex(
            model_name='licensetoken',
            index=models.Index(fields=['starts_at', 'expires_at'], name='licensing_l_starts__aecc2c_idx'),
        ),
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['ip'], name='licensing_h_ip_fc3f59_idx'),
        ),
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['uuid'], name='licensing_h_uuid_62b0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['created_at'], name='licensing_h_created_f5ffc6_idx'),
        ),
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['ip', 'created_at'], name='licensing_h_ip_851984_idx'),
        ),
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['uuid', 'created_at'], name='licensing_h_uuid_8f51e2_idx'),
        ),
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['license_token', 'created_at'], name='licensing_h_license_54076d_idx'),
        ),
    ]
